spring:
  application:
    name: KrishiYatra

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/krishi-yatra
      username: root
      password: WJ28@krphs

  jpa:
    hibernate:
      ddl-auto: none  # Flyway handles migrations
    show-sql: true

  h2:
    console:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:/db/stub-migration

springdoc:
  api-docs:
    version: openapi_3_0

  mail:
    host: smtp.gmail.com
    port: 587
    username: onlycoding6969@gmail.com
    password: dzwg ttjn dbst knib
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  otp:
    expiration-minutes: 5
    max-attempts: 5