-- Stub: Register user (user123) as a FARMER (isVerified = false)

-- Assign USER role
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID)
SELECT '550e8400-e29b-41d4-a716-446655440099', ROLE_GUID
FROM ROLES WHERE ROLE_NAME = 'FARMER';

-- Insert farmer record
INSERT INTO FARMERS (FARMER_GUID, FARM_NAME, FARM_LOCATION, FARM_AREA, FARM_TYPES, STATUS, USER_GUID, CREATED_TIME, CREATED_USER, MODIFIED_TIME, MODIFIED_USER)
VALUES ('f0000000-0000-0000-0000-000000000001', 'Green Valley Farm', 'Chitwan', 5.5, 'ORGANIC,VEGETABLE',
        'VERIFIED', '550e8400-e29b-41d4-a716-446655440099', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system');

-- Dummy Farmers (15)
-- Role assignments
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_01', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_02', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_03', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_04', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_05', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_06', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_07', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_08', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_09', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_10', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_11', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_12', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_13', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_14', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_f_15', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'FARMER';

-- Farmer Records
INSERT INTO FARMERS (FARMER_GUID, FARM_NAME, FARM_LOCATION, FARM_AREA, FARM_TYPES, STATUS, USER_GUID) VALUES
('f_id_01', 'Hari Farm', 'Bhaktapur', 5.5, 'Vegetables, Fruits', 'VERIFIED', 'u_f_01'),
('f_id_02', 'Sita Organic', 'Lalitpur', 3.2, 'Cereals', 'PENDING', 'u_f_02'),
('f_id_03', 'Ram Agri', 'Kathmandu', 10.0, 'Livestock', 'VERIFIED', 'u_f_03'),
('f_id_04', 'Gita Greens', 'Chitwan', 15.3, 'Vegetables', 'PENDING', 'u_f_04'),
('f_id_05', 'Shyam Poultry', 'Pokhara', 2.0, 'Poultry', 'VERIFIED', 'u_f_05'),
('f_id_06', 'Krishna Dairy', 'Butwal', 8.5, 'Dairy', 'PENDING', 'u_f_06'),
('f_id_07', 'Maya Florals', 'Banepa', 1.5, 'Flowers', 'VERIFIED', 'u_f_07'),
('f_id_08', 'Bishal Orchards', 'Dhading', 12.2, 'Fruits', 'PENDING', 'u_f_08'),
('f_id_09', 'Sunita Apiary', 'Gorkha', 0.5, 'Honey', 'VERIFIED', 'u_f_09'),
('f_id_10', 'Deepak Crops', 'Itahari', 20.0, 'Cereals', 'PENDING', 'u_f_10'),
('f_id_11', 'Prakash Seeds', 'Biratnagar', 4.5, 'Seeds', 'VERIFIED', 'u_f_11'),
('f_id_12', 'Anjali Spices', 'Illam', 2.5, 'Spices', 'PENDING', 'u_f_12'),
('f_id_13', 'Rajesh Coffee', 'Gulmi', 5.0, 'Coffee', 'VERIFIED', 'u_f_13'),
('f_id_14', 'Manoj Tea', 'Jhapa', 30.0, 'Tea', 'PENDING', 'u_f_14'),
('f_id_15', 'Kabita Mush', 'Kavre', 0.2, 'Mushroom', 'VERIFIED', 'u_f_15');
