CREATE TABLE USERS (
    USER_GUID VARCHAR(36) PRIMARY KEY,
    FULL_NAME VARCHAR(30) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    DELETED_AT TIMESTAMP NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(30),
    MODIFIED_TIME TIMESTAMP,
    MODIFIED_USER VARCHAR(30),
    PROFILE_URL VARCHAR(255),
    DESCRIPTION VARCHAR(1000)
);
