CREATE TABLE USERS (
    USER_GUID VARCHAR(36) PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255),
    PHONE_NUMBER VARCHAR(20),
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    DELETED_AT TIMESTAMP NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(50),
    MODIFIED_TIME TIMESTAMP NULL,
    MODIFIED_USER VARCHAR(50),
    PROFILE_URL VARCHAR(255),
    DESCRIPTION VARCHAR(1000)
) ENGINE=InnoDB;
