CREATE TABLE FIREBASE_TOKENS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_GUID VARCHAR(36) NOT NULL,
    FCM_TOKEN VARCHAR(512) NOT NULL,
    DEVICE_NAME VARCHAR(255),
    CONSTRAINT FK_FIREBASE_USER FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE NOTIFICATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    BODY TEXT NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    IS_READ BOOLEAN DEFAULT FALSE,
    IS_DELETED BOOLEAN DEFAULT FALSE,
    ACTION_URL VARCHAR(255),
    USER_GUID VARCHAR(36) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(50),
    MODIFIED_USER VARCHAR(50),
    CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID) ON DELETE CASCADE
) ENGINE=InnoDB;
