-- Re-create or Alter table to support OneToMany Entity association with PK
DROP TABLE IF EXISTS STOCK_IMAGES;
CREATE TABLE STOCK_IMAGES (
    IMAGE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    STOCK_GUID VARCHAR(36) NOT NULL,
    IMAGE_URL TEXT NOT NULL,
    IMAGE_ORDER INT NOT NULL DEFAULT 0,
    FOREIGN KEY (STOCK_GUID) REFERENCES STOCKS(STOCK_GUID) ON DELETE CASCADE
) ENGINE=InnoDB;
