CREATE TABLE IF NOT EXISTS FIREBASE_TOKENS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_GUID VARCHAR(36) NOT NULL,
    FCM_TOKEN VARCHAR(512) NOT NULL,
    DEVICE_NAME VARCHAR(255),
    CONSTRAINT fk_firebase_user FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID) ON DELETE CASCADE
);
