CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    BODY TEXT NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    IS_READ BOOLEAN DEFAULT FALSE,
    USER_GUID VARCHAR(255) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    CREATED_USER VARCHAR(255),
    MODIFIED_USER VARCHAR(255),
    CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID)
);
