CREATE TABLE ADDRESS (
    ADDRESS_GUID VARCHAR(36) PRIMARY KEY,
    PROVINCE VARCHAR(100),
    DISTRICT VARCHAR(100),
    MUNICIPALITY VARCHAR(100),
    WARD_NO INT,
    STREET_NAME VARCHAR(255),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(30),
    MODIFIED_TIME TIMESTAMP,
    MODIFIED_USER VARCHAR(30),

    USER_GUID VARCHAR(36) UNIQUE NOT NULL,

    CONSTRAINT FK_ADDRESS_USER FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID) ON DELETE CASCADE
);
