CREATE TABLE ROLES (
    ROLE_GUID VARCHAR(36) PRIMARY KEY,
    ROLE_NAME VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE USER_ROLES (
    USER_GUID VARCHAR(36) NOT NULL,
    ROLE_GUID VARCHAR(36) NOT NULL,
    PRIMARY KEY (USER_GUID, ROLE_GUID),
    FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID),
    FOREIGN KEY (ROLE_GUID) REFERENCES ROLES(ROLE_GUID)
);

-- Basic Roles
INSERT INTO ROLES (ROLE_GUID, ROLE_NAME) VALUES (UUID(), 'FARMER');
INSERT INTO ROLES (ROLE_GUID, ROLE_NAME) VALUES (UUID(), 'BUYER');
INSERT INTO ROLES (ROLE_GUID, ROLE_NAME) VALUES (UUID(), 'DELIVERY');
INSERT INTO ROLES (ROLE_GUID, ROLE_NAME) VALUES (UUID(), 'ADMIN');
