CREATE TABLE FARMERS (
    FARMER_GUID VARCHAR(36) PRIMARY KEY,
    FARM_NAME VARCHAR(255) NOT NULL,
    FARM_LOCATION VARCHAR(255) NOT NULL,
    FARM_AREA DOUBLE NOT NULL,
    FARM_TYPES VARCHAR(500), -- Stored as comma-separated values
    IS_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
    USER_GUID VARCHAR(36) NOT NULL UNIQUE,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(30),
    MODIFIED_TIME TIMESTAMP NULL,
    MODIFIED_USER VARCHAR(30),
    FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID)
);
