CREATE TABLE FARMERS (
    FARMER_GUID VARCHAR(36) PRIMARY KEY,
    FARM_NAME VARCHAR(255) NOT NULL,
    FARM_LOCATION VARCHAR(255) NOT NULL,
    FARM_AREA DOUBLE NOT NULL,
    FARM_TYPES VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    STATUS_MESSAGE VARCHAR(500),
    USER_GUID VARCHAR(36) NOT NULL UNIQUE,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(50),
    MODIFIED_TIME TIMESTAMP NULL,
    MODIFIED_USER VARCHAR(50),
    FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID) ON DELETE CASCADE
) ENGINE=InnoDB;
