CREATE TABLE BUYERS (
    BUYER_GUID VARCHAR(36) PRIMARY KEY,
    CONSUMER_TYPE VARCHAR(50) NOT NULL,
    BUSINESS_NAME VARCHAR(255) NOT NULL,
    BUSINESS_LOCATION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    STATUS_MESSAGE VARCHAR(500),
    USER_GUID VARCHAR(36) NOT NULL UNIQUE,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(30),
    MODIFIED_TIME TIMESTAMP NULL,
    MODIFIED_USER VARCHAR(30),
    FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID)
);
