CREATE TABLE DELIVERY (
    DELIVERY_GUID VARCHAR(36) PRIMARY KEY,
    VEHICLE_TYPE VARCHAR(30) NOT NULL,
    VEHICLE_BRAND VARCHAR(100) NOT NULL,
    NUMBER_PLATE VARCHAR(30) NOT NULL,
    LICENSE_NUMBER VARCHAR(50) NOT NULL,
    VEHICLE_PHOTO VARCHAR(255),
    LICENSE_PHOTO VARCHAR(255),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    STATUS_MESSAGE VARCHAR(500),
    USER_GUID VARCHAR(36) NOT NULL UNIQUE,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(50),
    MODIFIED_TIME TIMESTAMP NULL,
    MODIFIED_USER VARCHAR(50),
    FOREIGN KEY (USER_GUID) REFERENCES USERS(USER_GUID) ON DELETE CASCADE
) ENGINE=InnoDB;
