CREATE TABLE CATEGORY (
    CATEGORY_GUID VARCHAR(36) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(255) UNIQUE NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(30),
    MODIFIED_USER VARCHAR(30)
) ENGINE=InnoDB;

CREATE TABLE SUB_CATEGORY (
    SUB_CATEGORY_GUID VARCHAR(36) PRIMARY KEY,
    SUB_CATEGORY_NAME VARCHAR(255) UNIQUE NOT NULL,
    CATEGORY_GUID VARCHAR(36) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(30),
    MODIFIED_USER VARCHAR(30),
    FOREIGN KEY (CATEGORY_GUID) REFERENCES CATEGORY(CATEGORY_GUID)
) ENGINE=InnoDB;

CREATE TABLE STOCKS (
    STOCK_GUID VARCHAR(36) PRIMARY KEY,
    STOCK_NAME VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    STOCK_SLUG VARCHAR(255) UNIQUE NOT NULL,
    DESCRIPTION TEXT,
    QUANTITY DOUBLE NOT NULL,
    PRICE_PER_UNIT DOUBLE NOT NULL,
    MIN_QUANTITY INT NOT NULL DEFAULT 1,
    ACTIVE BOOLEAN DEFAULT TRUE,
    DELETED_AT DATE,
    FARMER_GUID VARCHAR(36) NOT NULL,
    CATEGORY_GUID VARCHAR(36) NOT NULL,
    SUB_CATEGORY_GUID VARCHAR(36) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(30),
    MODIFIED_USER VARCHAR(30),
    FOREIGN KEY (FARMER_GUID) REFERENCES FARMERS(FARMER_GUID),
    FOREIGN KEY (CATEGORY_GUID) REFERENCES CATEGORY(CATEGORY_GUID),
    FOREIGN KEY (SUB_CATEGORY_GUID) REFERENCES SUB_CATEGORY(SUB_CATEGORY_GUID)
) ENGINE=InnoDB;

CREATE TABLE STOCK_IMAGES (
    STOCK_GUID VARCHAR(36) NOT NULL,
    IMAGE_URL TEXT NOT NULL,
    FOREIGN KEY (STOCK_GUID) REFERENCES STOCKS(STOCK_GUID) ON DELETE CASCADE
) ENGINE=InnoDB;
