CREATE TABLE CATEGORY (
    CATEGORY_GUID VARCHAR(36) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(255) UNIQUE NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(30),
    MODIFIED_USER VARCHAR(30)
) ENGINE=InnoDB;

CREATE TABLE SUB_CATEGORY (
    SUB_CATEGORY_GUID VARCHAR(36) PRIMARY KEY,
    SUB_CATEGORY_NAME VARCHAR(255) UNIQUE NOT NULL,
    CATEGORY_GUID VARCHAR(36) UNIQUE NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(30),
    MODIFIED_USER VARCHAR(30),
    FOREIGN KEY (CATEGORY_GUID) REFERENCES CATEGORY(CATEGORY_GUID)
) ENGINE=InnoDB;

CREATE TABLE STOCKS (
    STOCK_GUID VARCHAR(36) PRIMARY KEY,
    STOCK_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STOCK_IMAGES TEXT, -- Stored as comma-separated or JSON
    QUANTITY DOUBLE NOT NULL,
    PRICE_PER_UNIT DOUBLE NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE,
    DELETED_AT DATE,
    FARMER_GUID VARCHAR(36) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(30),
    MODIFIED_USER VARCHAR(30),
    FOREIGN KEY (FARMER_GUID) REFERENCES FARMERS(FARMER_GUID)
) ENGINE=InnoDB;
