CREATE TABLE CATEGORY (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(255) UNIQUE NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(50),
    MODIFIED_USER VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE SUB_CATEGORY (
    SUB_CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    SUB_CATEGORY_NAME VARCHAR(255) UNIQUE NOT NULL,
    CATEGORY_ID INT NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(50),
    MODIFIED_USER VARCHAR(50),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) ON DELETE CASCADE
) ENGINE=InnoDB;
