CREATE TABLE STOCKS (
    STOCK_GUID VARCHAR(36) PRIMARY KEY,
    STOCK_NAME VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    STOCK_SLUG VARCHAR(255) UNIQUE NOT NULL,
    DESCRIPTION TEXT,
    QUANTITY DOUBLE NOT NULL,
    PRICE_PER_UNIT DOUBLE NOT NULL,
    MIN_QUANTITY INT NOT NULL DEFAULT 1,
    ACTIVE BOOLEAN DEFAULT TRUE,
    DELETED_AT DATE NULL,
    FARMER_GUID VARCHAR(36) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    SUB_CATEGORY_ID INT NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME TIMESTAMP NULL,
    CREATED_USER VARCHAR(50),
    MODIFIED_USER VARCHAR(50),
    FOREIGN KEY (FARMER_GUID) REFERENCES FARMERS(FARMER_GUID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES SUB_CATEGORY(SUB_CATEGORY_ID)
) ENGINE=InnoDB;

CREATE TABLE STOCK_IMAGES (
    IMAGE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    STOCK_GUID VARCHAR(36) NOT NULL,
    IMAGE_URL TEXT NOT NULL,
    IMAGE_ORDER INT NOT NULL DEFAULT 0,
    FOREIGN KEY (STOCK_GUID) REFERENCES STOCKS(STOCK_GUID) ON DELETE CASCADE
) ENGINE=InnoDB;
