-- Stub: Register user (user123) as a BUYER (isVerified = false)

-- Assign BUYER role
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID)
SELECT '550e8400-e29b-41d4-a716-446655440099', ROLE_GUID
FROM ROLES WHERE ROLE_NAME = 'BUYER';

-- Insert buyer record
INSERT INTO BUYERS (BUYER_GUID, CONSUMER_TYPE, BUSINESS_NAME, BUSINESS_LOCATION, IS_VERIFIED, USER_GUID, CREATED_TIME, CREATED_USER, MODIFIED_TIME, MODIFIED_USER)
VALUES ('b0000000-0000-0000-0000-000000000001', 'RESTAURANT', 'Himalayan Kitchen', 'Kathmandu',
        FALSE, '550e8400-e29b-41d4-a716-446655440099', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system');

-- Dummy Buyers (15)
-- Role assignments
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_01', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_02', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_03', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_04', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_05', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_06', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_07', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_08', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_09', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_10', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_11', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_12', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_13', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_14', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';
INSERT INTO USER_ROLES (USER_GUID, ROLE_GUID) SELECT 'u_b_15', ROLE_GUID FROM ROLES WHERE ROLE_NAME = 'BUYER';

-- Buyer Records
INSERT INTO BUYERS (BUYER_GUID, CONSUMER_TYPE, BUSINESS_NAME, BUSINESS_LOCATION, IS_VERIFIED, USER_GUID) VALUES
('b_id_01', 'RETAILER', 'Big Mart Chain', 'Kathmandu', TRUE, 'u_b_01'),
('b_id_02', 'RETAILER', 'Bhatbhateni Stores', 'Kathmandu', FALSE, 'u_b_02'),
('b_id_03', 'WHOLESALER', 'Green Grocery Ltd', 'Pokhara', TRUE, 'u_b_03'),
('b_id_04', 'HOTEL_RESTAURANT', 'Hotel Annapurna Complex', 'Kathmandu', FALSE, 'u_b_04'),
('b_id_05', 'INDIVIDUAL', 'Local Dealer Point', 'Chitwan', TRUE, 'u_b_05'),
('b_id_06', 'RETAILER', 'Fresh Mart Center', 'Butwal', FALSE, 'u_b_06'),
('b_id_07', 'WHOLESALER', 'Organic World Traders', 'Lalitpur', TRUE, 'u_b_07'),
('b_id_08', 'RETAILER', 'Namaste Superstore', 'Biratnagar', FALSE, 'u_b_08'),
('b_id_09', 'WHOLESALER', 'Valley Cold Store HQ', 'Balkhu', TRUE, 'u_b_09'),
('b_id_10', 'HOTEL_RESTAURANT', 'Restaurant Supply Hub', 'Kathmandu', FALSE, 'u_b_10'),
('b_id_11', 'WHOLESALER', 'Wholesale Agri Hub', 'Dharan', TRUE, 'u_b_11'),
('b_id_12', 'INDIVIDUAL', 'Direct Buy Hub', 'Itahari', FALSE, 'u_b_12'),
('b_id_13', 'WHOLESALER', 'Fair Trade Agri', 'Nepalgunj', TRUE, 'u_b_13'),
('b_id_14', 'RETAILER', 'City Mart Outlet', 'Banepa', FALSE, 'u_b_14'),
('b_id_15', 'WHOLESALER', 'Rural Link Suppliers', 'Hetauda', TRUE, 'u_b_15');
